
version: '3.4'
services:

  nginx:
    image: 'nginx:stable-alpine'
    ports: 
      - 80:80
      - 443:443
    tty: true
    depends_on: 
      - apiauth
      # - redis
      - mongodb
      - mongo-express
      # - portainer
    volumes: 
      # remember!!!!!!! add trust proxy to nodejs services
      - ../../app/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro #read only 

  # portainer:
  #   image: portainer/portainer-ce
  #   restart: always
  #   volumes:
  #     - portainer_data:/data
  #     - /var/run/docker.sock:/var/run/docker.sock 

  # redis:
  #   image: "redis:6.2.2-alpine"
  #   restart: always
  #   volumes:
  #     - redisvol:/var/lib/redis

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ../../app/services/db/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongovol:/data/db

  mongo-express:
    image: mongo-express
    restart: always 
    depends_on:
      - mongodb

  apiauth:
    build: 
      context: ../../app/services/auth
    restart: always
    depends_on:
      - mongodb
      # - redis
  
volumes:
  mongovol:
    driver: local
  portainer_data:
    driver: local
  # redisvol:
  #   driver: local