
version: '3.4'
services:

  nginx:
    stdin_open: true

  portainer:
    stdin_open: true

  redis:
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  mongodb:
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret

  mongo-express:
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_SITE_BASEURL=/__info__/mongo-express

  apiauth:
    build: 
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules 
      - ../app/services/auth:/app
    environment:
      - PORT=5002
      - DBURL=mongodb://<MONGOUSER>:<MONGOPASS>@mongodb:27017
      - DBNAME=vanillanodemongo
      - NODE_ENV=development
      - MONGOPASS=secret
      - MONGOUSER=root
      - CORS=http://localhost:3000
      - JWT_KEY=uy6hw65hywtrnbewhnterwhg
      - JWT_TTL=365d
    ports: 
      - 5002:5002


